#!/bin/sh
if [ -n "$_RTK_WRAP" ]; then
  PATH=$(echo "$PATH" | sed "s,/opt/rtk:,,g"); export PATH; exec gh "$@"
fi
case "$1" in
  pr|issue|run|api|release)
    export _RTK_WRAP=1; exec rtk gh "$@" ;;
  *) PATH=$(echo "$PATH" | sed "s,/opt/rtk:,,g"); export PATH; exec gh "$@" ;;
esac
