#!/bin/sh
if [ -n "$_RTK_WRAP" ]; then
  PATH=$(echo "$PATH" | sed "s,/opt/rtk:,,g"); export PATH; exec ruff "$@"
fi
case "$1" in
  check|format)
    export _RTK_WRAP=1; exec rtk ruff "$@" ;;
  *) PATH=$(echo "$PATH" | sed "s,/opt/rtk:,,g"); export PATH; exec ruff "$@" ;;
esac
